<div class="wrapper">
    <div class="mainWrap">
        <div class="main-module">
            <div class=head><H2>CQ Zone map</H2></div>
            <div class=body>
                <img src="/img/radio/cqzone.gif" alt="CQ Zone map" />
            </div>
        </div>
        <div class="main-module">
            <div class=head><H2>ITU Zone map</H2></div>
            <div class=body>
                <img src="/img/radio/ituzone.jpg" alt="ITU Zone map" />
            </div>
        </div>        
    </div>
    <div class="sideWrap">
        <div class="side-module">
            <div class="head"><h2>Digital</h2></div>
            <div class="body">
                
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>
        <div class="side-module">
            <div class="head"><h2>HF Transceivers/Amplifiers</h2></div>
            <div class="body">
                
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>   

        <div class="side-module">
            <div class="head"><h2>VHF/UHF Handhelds</h2></div>
            <div class="body">
                
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>  
        <div class="side-module">
            <div class="head"><h2>VHF/UHF Mobile Transceivers</h2></div>
            <div class="body">
                
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>           
    </div>
</div>