
		<div class="main-module">
            <div class=head><H2>Crypt</H2></div>
            <div class=body>
<?php echo $encrypt ?> <br />

<?php use Phalcon\Tag; ?>

<?php echo Tag::form('technology/crypt'); ?>

 <p>
    <label for="Salt">Salt</label>
    <?php echo Tag::textField("salt") ?>
 </p>

 <p>
    <label for="password">Password</label>
    <?php echo Tag::textField("password") ?>
 </p>

 <p>
    <?php echo Tag::submitButton("Encrypt") ?>
 </p>

</form>
            </div>
        </div>  
