	<div class="main-module">
		<div class="head"><h2>搜索结果</h2></div>
		<div class="body">
<!-- Google Search Result Snippet Begins -->
  <div id="results_008589143145807374698:f5uprauilyy"></div>
  <script type="text/javascript">
    var googleSearchIframeName = "results_008589143145807374698:f5uprauilyy";
    var googleSearchFormName = "searchbox_008589143145807374698:f5uprauilyy";
    var googleSearchFrameWidth = 600;
    var googleSearchFrameborder = 0;
    var googleSearchDomain = "www.google.com";
    var googleSearchPath = "/cse";
  </script>
  <script type="text/javascript" src="http://www.google.com/afsonline/show_afs_search.js"></script>
<!-- Google Search Result Snippet Ends -->	
	<div class="foot"></div>
	</div>