
		<div class="main-module">
            <div class=head><H2>Sha1</H2></div>
            <div class=body>
<?php echo $digest ?> <br />

<?php use Phalcon\Tag; ?>

<?php echo Tag::form('technology/sha1'); ?>

 <p>
    <label for="string">string</label>
    <?php echo Tag::textField("string") ?>
 </p>

 <p>
    <?php echo Tag::submitButton("Submit") ?>
 </p>

</form>
            </div>
        </div>  
	
