<?php use Phalcon\Tag; ?>
<div class="main-module">
    <div class=head><H2>Usb key 查询</H2></div>
    <div class=body>

    <?php echo Tag::form(array('technology/utility/usbtoken'));?>
    <p>
       <label for="usbkey">USB Token:</label>
       <?php echo Tag::textField(array("usbkey", 'size'=>32)) ?>
    </p>
    <p>
        <label for="version">Lib Version:</label>
        <?php echo Tag::textField("version") ?>
    </p>

    <p>
       <?php echo Tag::submitButton("Read") ?>
    </p>
    <p>该功只能运行在IE浏览器上</p>
    </form>

<OBJECT classid="clsid:C7672410-309E-4318-8B34-016EE77D6B58" id="ePass" name ="ePass" STYLE="LEFT: 0px; TOP: 0px" width="0" height="0" codebase="/usbtoken/install.cab"></OBJECT>
<script type="text/javascript">
try{
    var ePass = document.getElementById('ePass');
    var usbkey = document.getElementById('usbkey');
    var version = document.getElementById('version');
    ePass.OpenDevice(1,"");

    usbkey.value = ePass.GetStrProperty(7, 0, 0);
    version.value = ePass.GetLibVersion();

    ePass.CloseDevice();
}
catch(e){
    alert("请插入U盾");
}
</script>


    </div>
</div>
