<div class="side-module">
	<div class="head"><h2>工具箱</h2></div>
	<div class="body">
		<ul>
			<li>
				<a href="/technology/ip">IP归属地查询</a>
			</li>
         
			<li>
				<a href="/technology/myip">我的IP地址</a>
			</li>
       
			<li>
				<a href="/technology/crypt">crypt</a>
			</li>
			<li>
				<a href="/technology/md5">md5</a>
			</li>
			<li><a href="/technology/sha1">sha1</a></li>
			<li><a href="/technology/url">URL</a></li>
			<li><a href="/technology/base64">BASE64</a></li>
		</ul>
		<div class="divider solid"></div>
		<div class="foot-links"><a href=""></a></div>
	</div>
	<div class="foot"></div>
</div>
