<div class="wrapper">

<div class="mainWrap">


<div class="main-module">
	<div class="head"><h2>{#repeater#} 439.460 信号覆盖区</h2></div>
	<div class="body"> 
<style type="text/css">
#map {
    /* height: 180px; */
    width: 650px; 
    height: 300px;
} 
</style>
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
<div id="map"></div>
<script>

map = new OpenLayers.Map("map");
map.addLayer(new OpenLayers.Layer.OSM());
epsg4326 = new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)

var lonLat = new OpenLayers.LonLat(22.5854, 114.1088).transform(epsg4326, projectTo);

var zoom = 6;
map.setCenter(lonLat, zoom);

var vectorLayer = new OpenLayers.Layer.Vector("Overlay");

var point = new OpenLayers.Geometry.Point(lonLat.lon, lonLat.lat);


var mycircle = OpenLayers.Geometry.Polygon.createRegularPolygon
(
    point,
    50000,
    40,
    0
);

var featurecircle = new OpenLayers.Feature.Vector(mycircle);

var featurePoint = new OpenLayers.Feature.Vector(
    point,
    { description: 'info' },
    { externalGraphic: 'img/marker.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset: -12, graphicYOffset: -25 }
);
vectorLayer.addFeatures([featurePoint, featurecircle]);

map.addLayer(vectorLayer);


</script>

		<div id="map_canvas" style="width: 650px; height: 300px"></div>
		从最内测向外依次是,0.5w 手台,2W手台,5W手台+Yagi/5W车台+GP天线，车台全功率，罕见的成功通联。
		最外侧两个灰色覆盖区是，梧桐山顶手台覆盖区和罕见成功通联，曾经有火腿通联成功。
	</div>
	<div class=foot></div>
</div>	
<?php if ($is_manager){ ?>
<div class="side-module">
	<div class="head"><h2>Repeater Manager</h2></div>
	<div class="body">

<form id="radio.repeater" name="radio.repeater" method="post" action=""> 
<label for="mastership">{#mastership#}</label><input name="mastership" type="text" id="mastership" value="" size="-1" maxlength="" /><br /> 
<label for="province">{#province#}</label><input name="province" type="text" id="province" value="" size="4" maxlength="" /><br /> 
<label for="city">{#city#}</label><input name="city" type="text" id="city" value="" size="4" maxlength="" /><br /> 
<label for="frequency">{#frequency#}</label><input name="frequency" type="text" id="frequency" value="" size="-1" maxlength="" /><br /> 
<label for="shift">{#shift#}</label><input name="shift" type="text" id="shift" value="" size="2" maxlength="" /><br /> 
<label for="tone">{#tone#}</label><input name="tone" type="text" id="tone" value="" size="-1" maxlength="" /><br /> 
<label for="code">{#code#}</label><input name="code" type="text" id="code" value="" size="-1" maxlength="" /><br /> 
<label for="coordinate">{#coordinate#}</label><input name="coordinate" type="text" id="coordinate" value="" size="16" maxlength="" /><br /> 
<label for="status">{#status#}</label><input name="status" type="text" id="status" value="" size="1" maxlength="" /><br /> 
<label for="updated">{#updated#}</label><input name="updated" type="text" id="updated" value="" size="4" maxlength="" /><br /> 
<input type="submit" name="submit" id="submit" value="{#submit#}" /> 
<input type="reset" name="reset" id="reset" value="{#reset#}" /> 
</form> 

   	</div>
	<div class="foot"></div>
</div>
<?php } ?>
<div class="side-module">
	<div class="head"><h2>Hongkong VHF/UHF repeater</h2></div>
	<div class="body">
		<img src="http://i206.photobucket.com/albums/bb279/vr2xlb/Table-0.jpg" /> 	
   	</div>
	<div class="foot"></div>
</div>



</div>
<div class="sideWrap">
	<div class="side-module">
	  <div class="head">
		<h2>业余无线电中继台</h2>
	  </div>
	  <div class="body">
	  		<ul>
			<li>
				<a href="/radio/repeater/439.460">439.460</a>
			</li>
			<li>
				<a href="/photography/view/2014/BBBB/">BBBB</a>
			</li>
			<li>
				<a href="/photography/view/2014/KKK/">KKK</a>
			</li>
			<li>
				<a href="/photography/view/2014/aaa/">aaa</a>
			</li>
			<li>
				<a href="/photography/view/2014/golden/">golden</a>
			</li>
			</ul>
			<div class="divider solid"></div>
		<div class="foot-links"><a href="">添加中继</a> </div>
	  </div>
	  <div class="foot"></div>
	</div>
</div>

</div>