<div class="wrapper">

<div class="mainWrap">

	<div class="main-module">
		<div class="head"><h2><?php echo $collection.'/'.$album ?> - 著作权所有，禁止转载，禁止商业用途，商业用途，请联系本人。</h2></div>
		<div class="body">
		</div>
	</div>
<?php if($matrixs){ ?>
<?php foreach ($matrixs as $matrix) { ?>
	<div style="margin-left:5px;float:left;display:inline;">
		<?php  foreach ($matrix as $photo) { ?>

          <div style="width:165px;height:200px;background:#EEE;border:1px solid #ccc;text-align:center;float:left;margin:0 0 5px 5px;display:inline;overflow:hidden;">
            <div style="width:128px;margin:5px;">
                <a href="/photography/photo/<?php echo $collection?>/<?php echo $album ?>/<?php echo $photo ?>/" rel="nofollow">
                    <img src="/photography/thumbnail/<?php echo $collection?>/<?php echo $album ?>/<?php echo $photo ?>" alt="Thumbnail..."/>
                </a>
            </div>
          </div>		
		
		<?php } ?>
	</div>
<?php } ?>
<?php } ?>
		<!--
		<div class="gumball">
			<a href="/{$locale}/photography/photo/maximize/{$history}/{$photo_key}/{$row}">
			<img src="/{$locale}/photography/photo/thumbnail/{$history}/{$photo_key}/{$row}" alt="loading thumbnail..."/>
			</a>
		</div>
		-->

	<br clear="all" />
	<div class="default_page_nav">
		<div class="wrap">
			<div class="pages">
			Page <?php echo $pages['current'] ?> ... <?php echo $pages['count'] ?>
			</div>
			<div class="page_flipper">
			<a href="/photography/view/<?php echo $collection?>/<?php echo $album ?>/<?php echo $pages['first'] ?>">first</a> 
			<a href="/photography/view/<?php echo $collection?>/<?php echo $album ?>/<?php echo $pages['previous'] ?>">previous</a> 
			<a href="/photography/view/<?php echo $collection?>/<?php echo $album ?>/<?php echo $pages['next'] ?>">next</a> 
			<a href="/photography/view/<?php echo $collection?>/<?php echo $album ?>/<?php echo $pages['last'] ?>">last</a> 
			</div>
		</div>
	</div>
	

</div>
<div class="sideWrap">
	<div class="side-module">
	  <div class="head">
		<h2>Photo photos - <?php echo $collection ?>/<?php echo $album ?></h2>
	  </div>
	  <div class="body">
	  <?php if($albums){ ?>
		<ul>
		<?php  foreach ($albums as $photo) { ?>
			<li>
				<a href="/photography/view/<?php echo $collection?>/<?php echo $photo ?>/"><?php echo $photo ?></a>
			</li>
		<?php } /* <a href="/{$locale}/photography/photo/photo/{$history}/{$md5}/"><b style="color:orange">{$photo}</b></a> */ ?>
		</ul>
		<?php } ?>
		<div class="divider solid"></div>
		<div class="foot-links"><a href="/archives/public_html/photography/palm/index.html">Netkiller Photography 手札</a> </div>
	  </div>
	  <div class="foot"></div>
	</div>
</div>

</div>





