<?php use Phalcon\Tag; ?>
    <div class="main-module">
        <div class="head"><h2>呼号管理</h2></div>
        <div class="body"> 

        <table>
           <thead>
               <th>callsign</th>
               <th>description</th>
           </thead>
           <tbody>
               <?php foreach($callsigns as $callsign){ ?>
               <tr>
                   <td><a href="/radio/index/qrz/<?php echo $callsign->callsign ?>"><?php echo $callsign->callsign ?></td>
                   <td><?php echo $callsign->description ?></td>
               </tr>
               <?php }?>
           </tbody>
        </table>                

        </div>
        <div class=foot></div>
    </div>


    <div class="side-module">
        <div class="head"><h2>下列地址仅用于邮寄QSL卡片</h2></div>
        <div class="body">
       <?php /*
        if($callsign)
        Phalcon\Tag::setDefaults(array(
            "callsign" => $callsign->callsign,
            "description" => $callsign->description
             ));*/
        ?>
        <?php echo Tag::form("radio/profile/callsign"); //echo Phalcon\Tag::hiddenField(array("id", "value" => @$qth->_id));?>
        <table width="100%" border="0">
           <tr>
            <td><label for="callsign">callsign</label></td>
            <td><?php echo \Phalcon\Tag::textField(array("callsign", 'size'=>8, 'required'=>''));?></td>
          </tr>
          <tr>
              <td><label for="description">description</label></td>
              <td><?php echo Phalcon\Tag::textArea(array("description", "cols" => 90, "rows" => 4))?></td>
          </tr>
          <tr>
              <td></td>
              <td><?php echo Phalcon\Tag::checkField(array("default", "value" => "Y"));?> 目前正在使用</td>
          </tr>
          <tr>
            <td colspan="2">
                <?php echo Tag::submitButton("编辑") ?>
            </td>
          </tr>
        </table>
        </form>                
        </div>
        <div class="foot"></div>
    </div>