<?php use Phalcon\Tag; ?>
        <div class="main-module">
            <div class="head"><h2>业余无线电设台QSL卡片邮寄地址</h2></div>
            <div class="body"> 
            <?php if($qth){
                print(sprintf("地址：%s<br> 邮编：%s <br>收件人：%s<br>",$qth->address, $qth->zipcode, $qth->addressee));
            }?>
            </div>
            <div class=foot></div>
        </div>

        
        <div class="side-module">
            <div class="head"><h2>下列地址仅用于邮寄QSL卡片</h2></div>
            <div class="body">
           <?php 
            if($qth)
            Phalcon\Tag::setDefaults(array(
                "addressee" => $qth->addressee,
                "address"   => $qth->address,
                "zipcode"   => $qth->zipcode,
                "description" => $qth->description
                 ));
            ?>
            <?php echo Tag::form("radio/profile/qth"); echo Phalcon\Tag::hiddenField(array("id", "value" => @$qth->_id));?>
            <table width="100%" border="0">
               <tr>
                <td><label for="address">地址</label></td>
                <td><?php echo \Phalcon\Tag::textField(array("address", 'size'=>50, 'required'=>'')); ?></td>
              </tr>
                <td><label for="zipcode">邮编</label></td>
                <td><?php echo \Phalcon\Tag::textField(array("zipcode", 'size'=>6, 'required'=>'')); ?></td>
              </tr>
              <tr>
                <td><label for="addressee">收件人姓名</label></td>
                <td><?php echo Phalcon\Tag::textField(array("addressee", 'size'=>12, 'required'=>'')) ?></td>
              </tr>              
              <tr>
                  <td><label for="description">description</label></td>
                  <td><?php echo Phalcon\Tag::textArea(array("description", "cols" => 90, "rows" => 4))?></td>
              </tr>
              <tr>
                <td colspan="2">
                    <?php echo Tag::submitButton("编辑") ?>
                </td>
              </tr>
            </table>
            </form>                
            </div>
            <div class="foot"></div>
        </div>
