<div class="side-module">
	<div class="head"><h2>工具箱</h2></div>
	<div class="body">
		<ul>
			<li><a href="/technology/utility/ip">IP归属地查询</a></li>
			<li><a href="/technology/utility/myip">我的IP地址</a></li>
			<li><a href="/technology/utility/crypt">crypt 加密</a></li>
			<li><a href="/technology/utility/md5">md5 数字摘要</a></li>
			<li><a href="/technology/utility/sha1">sha1 数字摘要</a></li>
			<li><a href="/technology/utility/url">URL 编码/解码</a></li>
			<li><a href="/technology/utility/base64">BASE64 编码/解码</a></li>
            <li><a href="/technology/utility/crc32">CRC32 校验</a></li>
            <li><a href="/technology/utility/usbtoken">USB Token Tools</a></li>
            <li><a href="/technology/utility/soap">SOAP Debug Tools</a></li>
            <li><a href="/technology/utility/json">JSON Debug Tools</a></li>
            <li><a href="/technology/utility/hash_hmac">hash_hmac</a></li>
            <li><a href="/technology/utility/uniqid">uniqid</a></li>
		</ul>
		<div class="divider solid"></div>
		<div class="foot-links"><a href=""></a></div>
	</div>
	<div class="foot"></div>
</div>

<div class="side-module">
	<div class="head"><h2>读者分布图</h2></div>
	<div class="body">
		<div id="clustrmaps-widget"></div>
        <script type="text/javascript">var _clustrmaps = {'url' : 'http://netkiller.github.io', 'user' : 1107643, 'server' : '2', 'id' : 'clustrmaps-widget', 'version' : 1, 'date' : '2013-08-14', 'lang' : 'en', 'corners' : 'square' };(function (){ var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = 'http://www2.clustrmaps.com/counter/map.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);})();</script>
        <noscript><a href="http://www2.clustrmaps.com/user/87410e6bb"><img src="http://www2.clustrmaps.com/stats/maps-no_clusters/netkiller.github.io-thumb.jpg" alt="Locations of visitors to this page" /></a></noscript>
		<div class="divider solid"></div>
		<div class="foot-links"><a href=""></a></div>
	</div>
	<div class="foot"></div>
</div>
