<div class="side-module">
	<div class="head"><h2>{#net#} - <?php echo $net->datetime ?></h2></div>
	<div class="body"> 

<div><?php echo $net->frequency?> Radio net, <?php echo $net->topic ?>, control by <a href="/radio/index/qrz/<?php echo $net->host?>"><?php echo $net->host?></a></div>
<span></span>

	</div>
	<div class=foot></div>
</div>

<?php use Phalcon\Tag; ?>

<div class="main-module">
	<div class="head"><h2>{#net#} - Check IN !</h2></div>
	<div class="body"> 

<?php echo Tag::form("radio/net/checkin/".$id); ?>
<table>
	<tr>
		<td><label for="callsign">callsign</label></td>
		<td><label for="rst">rst</label></td>
		<td><label for="qth">QTH</label></td>
		<td><label for="device">device</label></td>
		<td><label for="watt">watt</label></td>
	</tr>
	<tr>
		<td><input name="callsign" type="text" id="callsign" value="" size="6" maxlength="6" required /></td>
		<td><input name="rst" type="text" id="rst" value="" size="3" maxlength="3" required /></td>
		<td><input name="qth" type="text" id="qth" value="" size="30" maxlength="50" required /></td>
		<td><input name="device" type="text" id="device" value="" size="30" maxlength="50" required /></td>
		<td><?php echo Tag::textField(array("watt",'required '=>'')) ?></td>
	</tr>
    <tr>
        <td colspan="4">
            Leave a message <input name="message" type="text" id="device" value="" size="30" maxlength="50" />
        </td>
    </tr>
    <tr>
        <td colspan="4"><input type="submit" name="submit" id="submit" value="Check In!" /> </td>
    </tr>
</table>
<input name="net_id" type="hidden" id="net_id" value="{$net->id}" /><br /> 
</form> 

<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
	<input name="net_id" type="hidden" id="net_id" value="{$net->id}" />
  <fieldset>
  <legend>{#logging#}</legend>
  <label for="userfile">{#logging#}</label>
  <input type="file" name="userfile" id="userfile" />
  <input type="submit" name="upload" id="upload" value="{#submit#}" />
  {$error}
  </fieldset>
</form>
	</div>
	<div class=foot></div>
</div>	

<script type="text/javascript">
$(document).ready(function(){
	$('#check').submit(function() {
		var error = false;
		if(!$('#callsign').val()){
			$("#callsign").css("border","2px solid orange");
			error = true
		}
		if(!$('#rst').val()){
			$("#rst").css("border","2px solid orange");
			error = true
		}
		
		$("input[type='text']").change( function() {
		  	$(this).css("border","1px solid black");
		});
		if(error){
			$("#dialog").dialog("open");
			return false;
		}
		return true;
	});	
});	
</script>

<div class="main-module">
	<div class="head"><h2>{#net#} {#logging#}</h2></div>
	<div class="body"> 

<table>
	<tr>
		<td>time</td>
		<td>callsign</td>
		<td>rst</td>
		<td>QTH</td>
		<td>device</td>
		<td>power</td>
        <td>message</td>
	</tr>
<?php foreach($checkins as $checkin) {?>
	<tr>
		<td><?php echo $checkin->datetime ?></td>
        <td><?php echo $checkin->callsign ?></td>
        <td><?php echo $checkin->rst ?></td>
        <td><?php echo $checkin->qth ?></td>
        <td><?php echo $checkin->device ?></td>
        <td><?php echo $checkin->watt ?></td>
        <td><?php echo $checkin->message ?></td>
	</tr>
<?php }?>
</table>

	</div>
	<div class=foot></div>
</div>