{strip}
<div class="side-module">
	<div class="head"><h2>{#net#} - {$net->datetime}</h2></div>
	<div class="body"> 

<div>{$net->frequency} Radio net, {$net->topic}, control by <a href="/{$locale}/radio/qrz/{$net->control}.html">{$net->control}</a></div>
<span></span>

	</div>
	<div class=foot></div>
</div>
{/strip}

{if $session.callsign}

<div class="main-module">
	<div class="head"><h2>{#net#} - Check IN !</h2></div>
	<div class="body"> 

<form id="check" name="check" method="post" action=""> 
<table>
	<tr>
		<td><label for="callsign">{#callsign#}</label></td>
		<td><label for="rst">{#rst#}</label></td>
		<td><label for="qth">QTH</label></td>
		<td><label for="device">{#device#}</label></td>
		<td></td>
	</tr>
	<tr>
		<td><input name="callsign" type="text" id="callsign" value="" size="6" maxlength="6" /></td>
		<td><input name="rst" type="text" id="rst" value="" size="3" maxlength="3" /></td>
		<td><input name="qth" type="text" id="qth" value="" size="30" maxlength="50" /></td>
		<td><input name="device" type="text" id="device" value="" size="30" maxlength="50" /></td>
		<td><input type="submit" name="submit" id="submit" value="Check In!" /> </td>
	</tr>
</table>
<input name="net_id" type="hidden" id="net_id" value="{$net->id}" /><br /> 
</form> 

<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
	<input name="net_id" type="hidden" id="net_id" value="{$net->id}" />
  <fieldset>
  <legend>{#logging#}</legend>
  <label for="userfile">{#logging#}</label>
  <input type="file" name="userfile" id="userfile" />
  <input type="submit" name="upload" id="upload" value="{#submit#}" />
  {$error}
  </fieldset>
</form>
	</div>
	<div class=foot></div>
</div>	

{literal}
<script type="text/javascript">
$(document).ready(function(){
	$('#check').submit(function() {
		var error = false;
		if(!$('#callsign').val()){
			$("#callsign").css("border","2px solid orange");
			error = true
		}
		if(!$('#rst').val()){
			$("#rst").css("border","2px solid orange");
			error = true
		}
		
		$("input[type='text']").change( function() {
		  	$(this).css("border","1px solid black");
		});
		if(error){
			$("#dialog").dialog("open");
			return false;
		}
		return true;
	});	
});	
</script>
{/literal}

{/if}

{strip}
<div class="main-module">
	<div class="head"><h2>{#net#} {#logging#}</h2></div>
	<div class="body"> 

<table>
	<tr>
		<td>{#number#}</td>
		<td>{#time#}</td>
		<td>{#callsign#}</td>
		<td>{#rst#}</td>
		<td>QTH</td>
		<td>{#device#}</td>
		<td>{#power#}</td>
	</tr>
{foreach from=$checks item=check}
	<tr>
		<td>{counter}</td>
		<td>{$check->time|date_format:"%H:%M"}</td>
		<td><a href="/{$locale}/radio/qrz/{$check->callsign|lower}.html">{$check->callsign}</a></td>
		<td>{$check->rst}</td>
		<td>{$check->qth}</td>
		<td>{$check->device}</td>
		<td>{$check->power}</td>
	</tr>
{/foreach}
</table>

	</div>
	<div class=foot></div>
</div>
{/strip}