<div class="main-module">
	<div class="head"><h2>{#net#}</h2></div>
	<div class="body"> 

<table>
	<tr>
		<td><label for="datetime">datetime</label></td>
		<td><label for="frequency">frequency</label></td>
		<td><label for="topic">topic</label></td>
        <td><label for="topic">host</label></td>
	</tr>
<?php foreach($nets as $net){ ?>
	<tr>
        <td><a href="/radio/net/log/<?php echo $net->_id ?>"><?php echo $net->datetime ?></a></td>
		<td><?php echo $net->frequency ?></td>
		<td><?php echo $net->topic ?></td>
		<td><a href="/radio/index/qrz/<?php echo $net->host ?>"><?php echo $net->host ?></a></td>
	</tr>
<?php }?>
</table>

	</div>
	<div class=foot></div>
</div>