<div class="side-module">
	<div class="head"><h2>{#net#} - <?php echo $net->datetime ?></h2></div>
	<div class="body"> 

<div><?php echo $net->frequency?> Radio net, <?php echo $net->topic ?>, control by <a href="/radio/index/qrz/<?php echo $net->host?>"><?php echo $net->host?></a></div>
<span></span>

	</div>
	<div class=foot></div>
</div>

<div class="main-module">
	<div class="head"><h2>Map</h2></div>
	<div class="body"> 
		<div id="map" style="width: 100%; height: 400px"></div>
	</div>
	<div class=foot></div>
</div>	

<script type="text/javascript">
var map = new BMap.Map("map");
map.centerAndZoom("重庆",12);

var pointA = new BMap.Point(106.486654,29.490295);  // 创建点坐标A--大渡口区
var pointB = new BMap.Point(106.581515,29.615467);  // 创建点坐标B--江北区
//alert('从大渡口区到江北区的距离是：'+map.getDistance(pointA,pointB)+' 米。');     //获取两点距离

var polyline = new BMap.Polyline([pointA,pointB], {strokeColor:"blue", strokeWeight:2, strokeOpacity:0.5});  //定义折线
map.addOverlay(polyline);   //添加折线到地图上
</script>

<div class="main-module">
	<div class="head"><h2>{#net#} {#logging#}</h2></div>
	<div class="body"> 

<table>
	<tr>
		<td>time</td>
		<td>callsign</td>
		<td>rst</td>
		<td>QTH</td>
		<td>device</td>
		<td>power</td>
        <td>message</td>
	</tr>
<?php foreach($checkins as $checkin) {?>
	<tr>
		<td><?php echo $checkin->datetime ?></td>
        <td><?php echo $checkin->callsign ?></td>
        <td><?php echo $checkin->rst ?></td>
        <td><?php echo $checkin->qth ?></td>
        <td><?php echo $checkin->device ?></td>
        <td><?php echo $checkin->watt ?></td>
        <td><?php echo $checkin->message ?></td>
	</tr>
<?php }?>
</table>

	</div>
	<div class=foot></div>
</div>