<style type="text/css">
#map{height:500px;width:700px;float:left;border-right:2px solid #bcbcbc;}
</style>
<div class="main-module">
	<div class="head"><h2>{#net#}</h2></div>
	<div class="body"> 

<div id="map"></div>

<script type="text/javascript">

// 百度地图API功能
var map = new BMap.Map("map");
var point   = null;
var marker  = null;

map.enableScrollWheelZoom();                            //启用滚轮放大缩小
<?php if($repeater){?>
point = new BMap.Point(<?php echo $repeater->coordinate ?>);
map.centerAndZoom(point,12);
marker = new BMap.Marker(point);
map.addOverlay(marker);
<?php }else{ ?>
map.centerAndZoom("中国",5);                   // 初始化地图,设置城市和地图级别。    
<?php } ?>
map.addEventListener("click", function(e){
    map.removeOverlay(marker);
    point = new BMap.Point(e.point.lng, e.point.lat);
    marker = new BMap.Marker(point);
    map.addOverlay(marker);
  document.getElementById("coordinate").value = e.point.lng + ", " + e.point.lat;
});

</script>             

	</div>
	<div class=foot></div>
</div>

<script type="text/javascript">
	$('#net').submit(function() {
		var error = false;
		if(!$('#datetime').val()){
			$("#datetime").css("border","2px solid orange");
			error = true
		}
		if(!$('#frequency').val()){
			$("#frequency").css("border","2px solid orange");
			error = true
		}
		if(!$('#control').val()){
			$("#control").css("border","2px solid orange");
			error = true
		}
		if(!$('#topic').val()){
			$("#topic").css("border","2px solid orange");
			error = true
		}
		if(!$('#coordinates').val()){
			$("#coordinates").css("border","2px solid orange");
			error = true
		}
		$("input[type='text']").change( function() {
		  	$(this).css("border","1px solid black");
		});
		if(error){
			$("#dialog").dialog("open");
			return false;
		}
		return true;
	});	
});	
</script>

<div class="main-module">
	<div class="head"><h2>{#net#}</h2></div>
	<div class="body"> 
<?php use Phalcon\Tag; ?>
<?php 
            if($repeater){
                Phalcon\Tag::setDefaults(array(
                    "callsign"  => $repeater->callsign?$repeater->callsign:$callsign,
                    "province"  => $repeater->province,
                    "city"      => $repeater->city,
                    "county"    => $repeater->county,
                    "frequency" => $repeater->frequency,
                    "shift"     => $repeater->shift,
                    "squelch"   => $repeater->squelch,
                    "code"      => $repeater->code,
                    'band'      => $repeater->band,
                    "coordinate"=> $repeater->coordinate,
                    "cq"        => $repeater->zone['cq'],
                    "itu"       => $repeater->zone['itu'],
                    "image"     => $repeater->image,
                    "status"    => $repeater->status,
                    "description" => $repeater->description
                    
                ));
            }else{
                Phalcon\Tag::setDefaults(array("host" => $callsign));
            }
            ?>
<?php echo Tag::form("radio/net/start"); ?>
<table>
	<tr>
		<td><label for="datetime">datetime(UTC)</label></td>
		<td><label for="frequency">frequency</label></td>
		<td><label for="host">host</label></td> 
		<td><label for="topic">topic</label></td>
		<td></td>
	</tr>
	<tr>
		<td><?php echo \Phalcon\Tag::tagHtml('input type="datetime" name="datetime" id="datetime" size=20 value="'.date('Y-m-d H:i:s').'"');?></td>
		<td><?php echo Tag::textField("frequency") ?></td>
		<td><?php echo Tag::textField("host") ?></td>
		<td><?php echo Tag::textField("topic") ?></td>
	</tr>
	<tr>
		<td colspan="4">
			<label for="coordinates">coordinates</label><?php echo Tag::textField("coordinate") ?>
		</td>
	</tr>
    <tr>
        <td colspan="4">
            <?php echo Tag::submitButton("submit") ?>
        </td>
    </tr>
</table> 
</form>
	</div>
	<div class=foot></div>
</div>	

<?php $this->partial("net/index") ?>