{if $session.callsign}
{strip}
<div class="main-module">
	<div class="head"><h2>{#net#}</h2></div>
	<div class="body"> 

<table>
	<tr>
		<td>{#number#}</td>
		<td><label for="datetime">{#date#}</label></td>
		<td><label for="datetime">{#time#}</label></td>
		<td><label for="frequency">{#frequency#}</label></td>
		<td><label for="topic">{#topic#}</label></td>
		<td><label for="control">{#control#}</label></td> 
	</tr>
{foreach from=$nets item=net}
	<tr>
		<td>{counter}</td>
		<td>{$net->datetime|date_format:"%Y:%m:%d"}</td>
		<td>{$net->datetime|date_format:"%H:%M"}</td>
		<td>{$net->frequency}</td>
		<td><a href="/{$locale}/radio/nets/check/{$net->id}.html">{$net->topic}</a></td>
		<td>{$net->control}</td>
	</tr>
{/foreach}
</table>

	</div>
	<div class=foot></div>
</div>
{/strip}

{literal}
<script type="text/javascript">
$(document).ready(function(){
	if (GBrowserIsCompatible()) {
		var map = new GMap2(document.getElementById("map_canvas"));
		map.addControl(new GLargeMapControl());
        map.addControl(new GScaleControl());
        map.enableScrollWheelZoom();
        map.addControl(new GMapTypeControl());
        map.addControl(new GOverviewMapControl());/*
		map.setMapType(G_DEFAULT_MAP_TYPE);
		*/
		map.setCenter(new GLatLng(22.5345, 114.0610), 10);
		
        GEvent.addListener(map, "click", function(marker, point) {
            if (marker) {
                $("#coordinates").val('');
                map.removeOverlay(marker);
            } else {
            	$("#coordinates").css("border","1px solid black");
                $("#coordinates").val(point);
                var coordinates = new GMarker(point);
                map.clearOverlays();
                map.addOverlay(coordinates);
            }
        });       
	}
	$('#net').submit(function() {
		var error = false;
		if(!$('#datetime').val()){
			$("#datetime").css("border","2px solid orange");
			error = true
		}
		if(!$('#frequency').val()){
			$("#frequency").css("border","2px solid orange");
			error = true
		}
		if(!$('#control').val()){
			$("#control").css("border","2px solid orange");
			error = true
		}
		if(!$('#topic').val()){
			$("#topic").css("border","2px solid orange");
			error = true
		}
		if(!$('#coordinates').val()){
			$("#coordinates").css("border","2px solid orange");
			error = true
		}
		$("input[type='text']").change( function() {
		  	$(this).css("border","1px solid black");
		});
		if(error){
			$("#dialog").dialog("open");
			return false;
		}
		return true;
	});	
});	
</script>
{/literal}
<div class="main-module">
	<div class="head"><h2>{#net#}</h2></div>
	<div class="body"> 

<form id="net" name="net" method="post" action=""> 
<table>
	<tr>
		<td><label for="datetime">{#datetime#}</label></td>
		<td><label for="frequency">{#frequency#}</label></td>
		<td><label for="control">{#control#}</label></td> 
		<td><label for="topic">{#topic#}</label></td>
		<td></td>
	</tr>
	<tr>
		<td><input name="datetime" type="text" id="datetime" value="{$datetime}" size="12" maxlength="16" /></td>
		<td><input name="frequency" type="text" id="frequency" value="" size="8" maxlength="8" /></td>
		<td><input name="control" type="text" id="control" value="{$session.callsign}" size="6" maxlength="6" /></td>
		<td><input name="topic" type="text" id="topic" value="" size="50" maxlength="255" /></td>
		<td><input type="submit" name="submit" id="submit" value="{#submit#}" /></td>
	</tr>
	<tr>
		<td colspan="4">
			<label for="coordinates">{#coordinates#}</label><input name="coordinates" type="text" id="coordinates" value="" size="40" maxlength="40" />
		</td>
	</tr>
</table> 
</form>
	
		<div id="map_canvas" style="width: 650px; height: 300px"></div>
	</div>
	<div class=foot></div>
</div>	
{/if}