<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=IoN3tUhZjq78v2DyeztYLQEO"></script>

<div class="wrapper">
    <div class="mainWrap">
        <?php echo $this->getContent() ?>
    </div>
    <div class="sideWrap">
        <div class="side-module">
            <div class="head"><h2> </h2></div>
            <div class="body">

                <div class="divider solid"></div>
                <div class="foot-links"></div>
            </div>
            <div class="foot"></div>
        </div>       
        
        <div class="side-module">
            <div class="head"><h2></h2></div>
            <div class="body">

                <div class="divider solid"></div>
                <div class="foot-links"></div>
            </div>
            <div class="foot"></div>
        </div>    
        
        <div class="side-module">
            <div class="head"><h2></h2></div>

                <div class="divider solid"></div>
                <div class="foot-links"><a href=""></a></div>
            </div>
            <div class="foot"></div>
        </div>            
    </div>
</div>
