<div class="wrapper">
    <div class="mainWrap">
        <?php echo $this->getContent() ?>
    </div>
    <div class="sideWrap">
        
        <div class="side-module">
            <div class="head"><h2></h2></div>
            <div class="body">
  
                <div class="divider solid"></div>
                <div class="foot-links"></div>
            </div>
            <div class="foot"></div>
        </div>       

        <div class="side-module">
            <div class="head"><h2></h2></div>
            <div class="body">
  
                <div class="divider solid"></div>
                <div class="foot-links"></div>
            </div>
            <div class="foot"></div>
        </div>               
        <div class="side-module">
            <div class="head"><h2></h2></div>
            <div class="body">

                <div class="divider solid"></div>
                <div class="foot-links"></div>
            </div>
            <div class="foot"></div>
        </div>         
    </div>
</div>