<div id="fullContainer">

<div id="bigContainer">



	<div class="main-module">
		<div class="head"><h2>{#itinerary#}</h2></div>
		<div class="body">
			<ol>
			{foreach from=$travels item=last10}
				<li><a href="/outdoor/travelogue/itinerary/%7B$last10-%3Eid%7D.html">{$last10-&gt;title}</a></li>
			{/foreach}
			</ol>
		</div>
	</div>
	
</div>
<div id="smallContainer">

<div class="side-module">
	<div class="head"><h2>摄影作品</h2></div>
	<div class="body">	
	<a href="/photography/"><img src="/img/slides.jpg" width="278"></a>
   	</div>
	<div class="foot"></div>
</div>	
{if $activities}
<div class="side-module">
	<div class="head"><h2>原最新活动</h2></div>
	<div class="body">
		<ol>
		{foreach from=$activities item=line}
			<li>
				<a href="/activity/item/%7B$line-%3Eid%7D.html">{$line-&gt;subject}</a>
			</li>
		{/foreach}
		</ol>
   	</div>
	<div class="foot"></div>
</div>
{/if}



	</div>

{*	
	<div id="leftColumn">
		{include file="left.tpl"}
	</div>	

	<div id="rightColumn">
		{include file="right.tpl"}
	</div>
*}	

</div>
{*
<br clear="all">

<table width="100%">
	<tbody><tr>
	<td valign="top">	
	<div class="main-module">
		<div class="head"><h2>摄影</h2></div>
		<div class="body">
		<ol>
		{foreach from=$rss.digital.items item=i}
			<li><a href="http://netkiller.users.sourceforge.net/%7B$i.link%7D">{$i.title}</a></li>
		{/foreach}
		</ol>
	   	</div>
		<div class="foot"></div>
	</div>
	</td>
	<td valign="top">
	<div class="main-module">
		<div class="head"><h2>户外运动</h2></div>
		<div class="body">
		<ol>
		{foreach from=$rss.car.items item=i}
			<li><a href="http://netkiller.users.sourceforge.net/%7B$i.link%7D">{$i.title}</a></li>
		{/foreach}
		</ol>
	   	</div>
		<div class="foot"></div>
	</div>
	</td>
	<td valign="top">
	<div class="main-module">
		<div class="head"><h2>业余无线电</h2></div>
		<div class="body">
		<ol>
		{foreach from=$rss.book.items item=i}
			<li><a href="http://netkiller.users.sourceforge.net/%7B$i.link%7D">{$i.title}</a></li>
		{/foreach}
		</ol>
	   	</div>
		<div class="foot"></div>
	</div>	
		
	</td>
	</tr>
</tbody></table>
    <?php echo $this->getContent() ?>
    <hr>
<?php 
echo Phalcon\Tag::linkTo("signup", "Sign Up Here!");
?>

<table width="100%">
    <tbody><tr>
    <td valign="top">



    </td>
    <td valign="top">



    
    </td>
    <td valign="top">

    </td>
    </tr>
</tbody></table>




