<div id="global-footer">
  	<div class="first">
		<span>版权所有,侵权必究,法律顾问 <a href="http://www.arclawyer.cn/">广东广和律师事务所</a>孙建武律师(<a href="/radio/qrz/bg7nhl.html">BG7NHL</a>)</span>
	</div>
	<div class="second">
		<a href="http://tuhuli.com/">土狐狸 </a> &nbsp;|&nbsp;
		<a href="http://lhbc.sq.ez369.cn/">易众社区</a> &nbsp;|&nbsp; 
		<a href="http://zyr.hk/">自由人俱乐部</a> 
	</div>
	<div class="third"> 
  		<a href="/home/about.html">About</a> | 
  		<a href="/home/contact.html">Contact us</a> | 
  		<a href="http://netkiller.users.sourceforge.net/sitemaps/technology.xml">Sitemaps</a> |
  		<a href="http://netkiller.users.sourceforge.net/#">FAQs</a> | 
  		<a href="http://netkiller.users.sourceforge.net/#">Affiliates</a> | 
  		<a href="http://netkiller.users.sourceforge.net/#">Privacy policy </a>
	</div>
	
	<div> <a href="http://validator.w3.org/check?uri=referer" target="_blank"> <img alt="XHTML 1.0 Transitional" src="/img/xhtml.png" border="0"> </a> <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank"> <img alt="Css Validator" src="/img/css.png" border="0"> </a> <a href="http://netkiller.users.sourceforge.net/new.xml" target="_blank"> <img alt="RSS 2.0" src="/img/rss2.png" border="0"> </a> <a href="http://www.mozilla.org/products/firefox/" target="_blank"> <img alt="Get firefox" src="/img/firefox.gif" border="0"> </a> </div>
	<div> Copyright ? 2007 - 2009 Neo All Rights Reserved. {*Group Limited*} </div>
	<footer>
        <p>&copy; 2007 - 2009 Neo All Rights Reserved. </p>
    </footer>
</div>

