
<link rel="stylesheet" href="/css/photo.css" type="text/css" media="all" />
<div class="wrapper">

<div class="mainWrap">

<div class=main-module>
		<div class=head><h2><?php echo $imagepath ?></h2></div>
		<div class=body>

	
<!--			
		<div style="float:none">
			<ul>
				<li style="float:left;">图片名称：{$preview.name}</li>
				<li style="float:right;">图片作者：<a href="/profile/{$preview.id}/">{$preview.username}</a></li>
			</ul>
		</div>
	
		{if $isfull }

			<div id="photoview" style="width: 959px">
			<a href="/photos/preview/{$preview.id}/">
			<img id="photo" src="/photography/image/<?php echo $imagepath ?>" onload="javascript:if(this.width > this.height){if(this.width>800) this.width=800;}else{if(this.height>800) this.height=800;}" />
			</a>
			</div>
		{else}
-->			
			<div class="view">
			<a href="/photography/collection/slide/<?php echo $imagepath ?>">
				<img id="photo" src="/photography/collection/image/<?php echo $imagepath ?>" onload="javascript:if(this.width>670) this.width=670;" />
			</a>
			</div>
			
		<div class="control">
	
		</div>
<!--
		<div class="description">
		{#description#}：{$preview.description}
		</div>
		{if $preview.camera}
		<div class="camera">
			{#camera#}：{$preview.camera}
		</div>
		{/if}
		{if $preview.lens}
		<div class="lens">
			{#lens#}：{$preview.lens}
		</div>
		{/if}
-->		
	</div>

	</div>
<?php

?>


<div class="photo_relate">
	<?php foreach($related as $image) { ?>
	<div class="relate">
		<a href="/photography/collection/photo/<?php echo $collection?>/<?php echo $album ?>/<?php echo $image ?>" rel="nofollow">
        <img src="/photography/collection/thumbnail/<?php echo $collection?>/<?php echo $album ?>/<?php echo $image ?>" alt="Thumbnail..."/>
		</a>
	</div>
	<?php } ?>
</div>



<!--	
	<div id="feedback">
		<dl>
			<dt>最新留言</dt>
			{if $comments}
				<dd>
				{foreach from=$comments item=comment}
				<ul>
					<li style="padding-left:5px; ">{$comment.username}: </li>
					<li>{$comment.comment}</li>
					<li style="float:right;">{$comment.created}</li>
				</ul>
				<br clear="all" />
				{/foreach}
				</dd>
			{else}
				<dd>没有评论</dd>
			{/if}
			
		</dl>
	</div>
-->	


</div>
<div class="sideWrap">
<div class="side-module">
  <div class="head">
    <h2>EXIF Parameters</h2>
  </div>
  <div class="body" style="padding:5px 0px 0px 0px;">
	<?php if ($exif){ ?>
	<ul>
		<?php foreach($exif as $key=>$value) {?>
		<li>&nbsp;&nbsp;<?php echo $key ?> : <?php echo $value ?> </li>
		<?php } ?>
	</ul>
	<?php }else{ ?>
		&nbsp;&nbsp;&nbsp; NO EXIF
	<?php } ?>
    <div class="divider solid"></div>
    <div class=foot-links><a href="/{$locale}/photography/home/about/exif.html">About EXIF Parameters</a> </div>
  </div>
  <div class=foot></div>
</div>

<div class="side-module">
  <div class="head">
    <h2>RGB Histogram</h2>
  </div>
  <div class="body" style="padding:0px;">
 	<img src="/photography/collection/histogram/<?php echo $imagepath?>" width=245 />
    <div class="divider solid"></div>
    <div class=foot-links><a href="/{$locale}/photography/home/about/histogram.html">About RGB Histogram</a> </div>
  </div>
  <div class=foot></div>
</div>

    <div class="side-module">
        <div class="head"><h2>拍摄地点</h2></div>
        <div class="body">

            <div class="divider solid"></div>
            <div class="foot-links">  </div>
        </div>
        <div class="foot"></div>
    </div>
    
    <div class="side-module">
        <div class="head"><h2>一些常用光源的色温为</h2></div>
        <div class="body">
            <ul> 
              <li>标准烛光为1930K（开尔文温度单位）；</li> 
              <li>钨丝灯为2760-2900K；</li>				
              <li>荧光灯为3000K；</li>			
              <li>闪光灯为3800K；</li>			
              <li>中午阳光为5400K；</li>	
              <li>电子闪光灯为6000K；</li> 
              <li>蓝天为12000-18000K。</li> 
            </ul> 

            <div class="divider solid"></div>
            <div class="foot-links">  </div>
        </div>
        <div class="foot"></div>
    </div>
</div>
</div>