<div id="bigContainer">

	<div class=main-module id=tagging>
		<div class=head><h2>2014年业余无线电竞赛月历</h2></div>
		<div class=body>
            <pre>
 2014年竞赛月历（1月）

·        1月1日0800～1100 
名称：斯堪的纳维亚业余无线电协会新年无线电传比赛（SARTG New Year RTTYContest）
波段、模式：80m、40m、RTTY
信号报告：RST+QSO序列号+名字+Happy New Year
·        1月1日0900～1200
名称：德国AGCW协会新年比赛（AGCW Happy New YearContest）
波段、模式：80m、40m、20m、CW
信号报告：AGCW会员：RST+序列号+“/”+会员号；非AGCW会员：RST+序列号
·        1月4日1800～5日2400
名称：美国无线电联盟无线电传围捕赛（ARRL RTTY Roundup）
波段、模式：80m、40m、20m、15m、10m、RTTY、Digital
信号报告：美国、加拿大电台：RST+州名；非美国、加拿大电台：RST+序列号    
·        1月4日2000～2300；5日0400～0700
名称：欧洲CW联盟160m波段比赛（EUCW 160m Contest）
波段、模式：160m、CW
信号报告：俱乐部成员：RST+名字+俱乐部名+会员号；其他：RST+名字+NM
·        1月11日1800～12日0600
名称：北美QSO派对（North American QSO Party,CW）
波段、模式：160m、80m、40m、20m、15m、10m、CW
信号报告：北美电台：名字+州名；非北美电台：名字
·        1月12日0900～1059
名称：德国业余无线电俱乐部10m波段比赛（DARC 10 Meter Contest）
波段、模式：10m、CW、SSB
信号报告：德国电台：RS(T)+QSO数目+DOK；非德国电台：RS(T)+QSO数目
·        1月12日1000～1400
名称：仲冬比赛
 


            </pre>
		</div>
	</div>
	<div class="main-module">
	    <div class="head"><h2>Midwinter Contest</h2></div>
	    <div class="body">
            <pre>
（Midwinter Contest）1月12日1000～1400
波段、模式：80m、40m、20m、15m、10m、CW、SSB
信号报告：女：RST+序列号（2001开始）；男：RST+序列号（001开始）
·        1月18日1200～19日1200
名称：匈牙利DX比赛（Hungarian DX Contest）
波段、模式：160m、80m、40m、20m、15m、10m、CW、SSB
信号报告：匈牙利电台：RS(T)+县名；非匈牙利电台：RS(T)+序列号
·        1月18日1800～19日0559
名称：北美QSO派对（North American QSO Party,SSB）
波段、模式：160m、80m、40m、20m、15m、10m、SSB
信号报告：北美电台：名字+州名；非北美电台：名字
·        1月24日2200～26日2159
名称：CQ160m波段CW比赛（CQ 160 Meter Contest, CW）
波段、模式：160m、CW
信号报告：美国、加拿大电台：RST+州名；DX电台：RST+CQ分区号
·        1月25日1200～26日1200
名称：英国业余无线电协会无线电传追逐赛（BARTG RTTY Sprint）
波段、模式：80m、40m、20m、15m、10m、RTTY
信号报告：序列号                 
            </pre>
        </div>
        <div class="foot"></div>
	</div>
	<div class="main-module">
		<div class="head"><h2>Ham Activity</h2></div>
		<div class="body">

		</div>
	</div>
    <div class="main-module">
        <div class=head><H2>LATEST NEWS</H2></div>
        <div class=body>

        </div>
        <div class="foot"></div>
    </div>

</div>

<div id="smallContainer">

<div class="side-module">
	<div class="head"><h2>呼号查询</h2></div>
	<div class="body">
		<form method="get" name="qrz" id="qrz">
		callsign <input type="text" id="qrz" name="qrz" value="" size="6" maxlength="6" />
		<input type="submit" value="search" id="go" name="go"/>
		</form>
	</div>
	<div class=foot></div>
</div>
<div id="dashboard">
</div>


<div class="side-module">
	<div class="head"><h2>QSO {#ranging#}</h2></div>
	<div class="body">
		<form method="post" name="qsoform" id="qsoform">
		{#callsign#} <input type="text" id="qso" name="qso" value="BG7NYT-BI7JMS-BH7MXG" onclick="this.value='';"size="18" maxlength="20" />
		<input type="submit" value="{#ranging#}" id="ranging" name="ranging"/><br />
		使用“-”分割呼号,呼号个数不限制。
		<form>
	</div>
	<div class=foot></div>
</div>

<div class=side-module>
	<div class=head><H2>Welcome to QSO</H2></div>
	<div class=body>
		<ul>
		  <li>Personal Amateur Radiostations of P.R.China</li>
		  <li>ZONE CQ24 ITU44 ShenZhen, China</li>
		  <li>QTH: Longhua Shenzhen, China</li>
		  <li>Callsign: BG7NYT No.72-50335</li>
		  <li>Best Regards, VY 73! OP. BG7NYT</li>
		</ul>
   	</div>
	<div class=foot></div>
</div>
<div class=side-module>
	<div class=head><H2>Ham {#resource#}</H2></div>
	<div class=body>
		<ul>
		  <li><a href="/{$locale}/radio/placemark/ham.kml">Google Earth Placemark (KML)</a></li>
		  <li><a href="/{$locale}/radio/placemark/ham.kmz">Google Earth Placemark (KMZ)</a></li>
		</ul>
   	</div>
	<div class=foot></div>
</div>
<div class=side-module>
	<div class=head><H2>Links</H2></div>
	<div class=body>
		<ul>
		  <li>http://www.iaru.org/</li>
		  <li>http://www.qrz.com/</li>
		  <li>http://www.qrz.cn/</li>
		  <li>http://www.szham.org</li>
		  <li>http://www.hellocq.net</li>
		  <li>http://www.hellocq.com</li>

		</ul>
   	</div>
	<div class=foot></div>
</div>

</div>
