<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=IoN3tUhZjq78v2DyeztYLQEO"></script>
<div class="wrapper">
    <div class="mainWrap">
        <?php echo $this->getContent() ?>
    </div>
    <div class="sideWrap">
        <div class="side-module">
            <div class="head"><h2>最活跃的主控</h2></div>
            <div class="body">
                <ul>
                    <li><a href="/radio/profile/callsign"></a></li>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/net">台网主页</a></div>
            </div>
            <div class="foot"></div>
        </div>        
    </div>
</div>