<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=IoN3tUhZjq78v2DyeztYLQEO"></script>

<div class="wrapper">
    <div class="mainWrap">
        <?php echo $this->getContent() ?>
    </div>
    <div class="sideWrap">
        <div class="side-module">
            <div class="head"><h2>业余无线电台资料管理</h2></div>
            <div class="body">
                <ul>
                    <li><a href="/radio/profile/callsign">呼号管理</a></li>
                    <li><a href="/radio/profile/signaling">信令ID管理</a></li>
                    <li><a href="/radio/profile/qth">设台资料管理</a></li>
                    <li><a href="/radio/profile/mail">QSL卡片邮寄地址管理</a></li>
                    <li><a href="/radio/qsl">QSL卡片管理</a></li>
                    <li><a href="/radio/profile/equipment">火腿装备管理</a></li>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>       

        <div class="side-module">
            <div class="head"><h2>业余无线电台日志管理</h2></div>
            <div class="body">
                <ul>
                    <li><a href="/radio/profile/logging/">电台日志管理</a></li>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>            
        
        <div class="side-module">
            <div class="head"><h2>中继，信标，台网管理</h2></div>
            <div class="body">
                <ul>
                    
                    <li><a href="/radio/profile/repeater">中继台管理</a></li>
                    <li><a href="/radio/beacon/mgmt/">信标台管理</a></li>
                    <li><a href="/radio/profile/net">无线电台网</a></li>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/">业余无线主页</a></div>
            </div>
            <div class="foot"></div>
        </div>    
        
        
        <?php if($callings) {?>
        <div class="side-module">
            <div class="head"><h2>业余无线电被叫清单</h2></div>
            <div class="body">
                <ul>
            <?php foreach ($callings as $calling){?>
                <li>
                    <?php echo $calling->callsign;?> <a href="/radio/index/qrz/<?php echo $calling->callsign;?>">查看</a>
                </li>
            <?php }?>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/logging/">电台操作日志</a></div>
            </div>
            <div class="foot"></div>
        </div>                
        <?php }?>
        
        <?php if ($stations){ ?>   
        <div class="side-module">
            <div class="head"><h2>业余无线电中继站管理</h2></div>
            <div class="body">
                <ul>
            <?php foreach ($stations as $station){?>
                <li>
                    <?php echo $station->frequency;?> <?php echo $station->name;?> <a href="/radio/repeater/details/<?php echo $station->_id;?>">预览</a>|<a href="/radio/repeater/mgmt/<?php echo $station->_id;?>">编辑</a>
                </li>
            <?php }?>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/radio/repeater/mgmt/">新增中继台</a> | <a href="/radio/profile/">返回</a> </div>
            </div>
            <div class="foot"></div>
        </div>
        <?php } ?>
    </div>
</div>
