<!DOCTYPE html>
<html>
<head>
    <?php echo $this->tag->getTitle() ?>
    <link href="/css/theme.css" rel="stylesheet" rev="stylesheet" type="text/css" media="all">
    <style type="text/css">
body,table,input,textarea,select {font-family:微软雅黑,Verdana,sans-serif,宋体;}  
    </style>
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    </head>
<body>
<div id="global-header">
    <?php $this->partial("../../views/shared/channel") ?>	
	<div id="masthead">
		<div id="logo">
            <a href="http://www.crsa.org"><img src="/img/radio/crsa.jpg" height="75" alt="CRSA"></a>
            <!--
			<img src="/img/freebsd.png" height="75" alt="freebsd logo">
			<img src="/img/linux.png" height="75" alt="linux logo">
			<img src="/img/openbsd.png" height="75" alt="openbsd logo">
			<img src="/img/gnu.png" height="75" alt="gnu logo">
            -->
		</div>
		<div id="banner">
            
            
            <a href="http://www.hkara.org.hk/"><img src="/img/radio/hkara.gif" height="75" alt="HKARA"></a>
            <a href="http://www.arrl.org/"><img src="/img/radio/arrl.png" height="75" alt="ARRL"></a>
            
		</div>
	</div>
	<div class="navigation">
		<ul>
		<?php 
            if(count($this->elements->getMenu($_GET['_url'])) > 1){
                $menuitem = $this->elements->getMenu($_GET['_url']);
            }else{
                $menuitem = $this->elements->getChannel();
            }
            ?>
            <li class="on"><?php echo Phalcon\Tag::linkTo( '','Home');?></a></li>
            <?php  foreach( $menuitem as $menu) {?>
			<li class="on"><?php echo Phalcon\Tag::linkTo(array( $menu['link'], $menu['title'], 'target'=>"_parent"/*, 'class' => ''*/));?></a></li>
            <?php }?>
		<!--
		<li {if="" $mainmenu="" eq="" ''="" or="" 'index'}="" class="on" {="" if}=""><a href="/index.html" target="_parent">{#home#}</a></li>
		<li {if="" $mainmenu="" eq="" 'technology'}="" class="on" {="" if}=""><a href="/technology/index.html" target="_parent">{#technology#}</a></li>
		<li {if="" $mainmenu="" eq="" 'photography'}="" class="on" {="" if}=""><a href="/photography/index.html" target="_parent">{#photography#}</a></li>
		<li {if="" $mainmenu="" eq="" 'radio'}="" class="on" {="" if}=""><a href="/radio/index.html" target="_parent">{#radio#}</a></li>
        <li {if="" $mainmenu="" eq="" 'outdoor'}="" class="on" {="" if}=""><a href="/outdoor/index.html" target="_parent">{#outdoor#}</a></li>
        <li {if="" $mainmenu="" eq="" 'music'}="" class="on" {="" if}=""><a href="/music/index.html">{#music#}</a></li>
		<li {if="" $mainmenu="" eq="" 'activity'}="" class="on" {="" if}=""><a href="/activity/index.html" target="_parent">{#activity#}</a></li>
		<li {if="" $mainmenu="" eq="" 'groups'}="" class="on" {="" if}=""><a href="/groups/index.html" target="_parent">{#group#}</a></li>		
		<li {if="" $mainmenu="" eq="" 'member'}="" class="on" {="" if}=""><a href="/member/index.html" target="_parent">{#member#}</a></li>
		<li {if="" $mainmenu="" eq="" 'guestbook'}="" class="on" {="" if}=""><a href="/member/guestbook.html" target="_parent">{#guestbook#}?????</a></li>
		-->
		</ul>
	<ul style="float:right;">
		<li>
<!-- Google CSE Search Box Begins -->
  <form id="searchbox_008589143145807374698:f5uprauilyy" action="/technology/search/">
    <input type="hidden" name="cx" value="008589143145807374698:f5uprauilyy" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="25" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=searchbox_008589143145807374698%3Af5uprauilyy"></script>
<!-- Google CSE Search Box Ends -->
		</li>
	</ul>
</div>
<?php if($this->elements->getSubmenu($_GET['_url'])){ ?>
<div class="subnav">
	<ul>
	<?php foreach( $this->elements->getSubmenu($_GET['_url']) as $submenu) {?>
	<li class="on"><a href="<?php echo $submenu['link']?>" target="_parent"><?php echo $submenu['title']?></a></li>
	<?php }?>
	<ul>
</div>
<?php } ?>

</div>

<!--
<div class="sidebar">
<ul class="menu">
    <li><a href="/">Home</a></li>
    <li><a href="/articles">Articles</a></li>
    <li><a href="/contact">Contact us</a></li>
</ul>
</div>
-->

<div id="container">

<?php echo $this->getContent() ?>

</div>

<br clear="all">
    <?php $this->partial("../../views/shared/footer") ?>
</body>
</html>
