<script type="text/javascript">
</script>
<!--
<div class="main-module">
	<div class="head"><h2>{#logging#}</h2></div>
	<div class="body"> 
		<div id="map_canvas" style="width: 650px; height: 300px"></div>
	</div>
	<div class=foot></div>
</div>	-->



<script type="text/javascript">
$(document).ready(function(){

	$('#logging').submit(function() {
		if($('#logging_callsign').val()){
	    	window.location.href='/zh-cn/radio/logs/'+$('#logging_callsign').val()+'.html';
	    }
	    return false;
	});
	
});
</script>



<?php if($loggings){ ?>

        <div class="main-module">
            <div class="head"><h2>业余电台通联日志</h2></div>
            <div class="body"> 
            <table>
               <thead>
                   <th>callsign</th>
                   <th>date</th>
                   <th>time</th>
                   <th>frequency(Mhz)</th>
                   <th>mode</th>
                   <th>call</th>
                   <th>rst</th>
                   <th>watt</th>
                   <th>notes</th>
               </thead>
               <tbody>
                   <?php foreach($loggings as $log){ ?>
                   <tr>
                       <td><a href="/{$locale}/radio/logs/{$log->callsign|lower}.html"><?php echo $log->callsign ?></td>
                       <td><?php echo $log->date ?></td>
                       <td><?php echo $log->time ?></td>
                       <td><?php echo $log->frequency ?></td>
                       <td><?php echo $log->mode ?></td>
                       <td><a href="/{$locale}/radio/qrz/{$log->call|lower}.html"><?php echo $log->call ?></td>
                       <td><?php echo $log->rst ?></td>
                       <td><?php echo $log->watt ?></td>
                       <td><?php echo $log->notes ?></td>
                   </tr>
                   <?php }?>
               </tbody>
            </table>
            </div>
            <div class=foot></div>
        </div>
<?php }else{ ?>

没有在本站留下通联日志信息. <br />
<?php } ?>
<pre>        
<?//php print_r($loggings)?>
</pre>