	<div class="main-module">
		<div class="head"><h2>HF傳播預測</h2></div>
		<div class="body">
			<iframe src="http://www.hamtalk.asia/prop/PropShow.htm" width="100%" height="210" scrolling="no" frameborder="0">
            HAMTALK使用了框架技术，但是您的浏览器不支持框架，请升级您的浏览器以便正常访问HAMTALK。
            </iframe>
		</div>
	</div>	
	
<div class="main-module">
	<div class="head"><h2>汉化版本</h2></div>
	<div class="body"> 
		<ul>
			<li><a href="/archives/public_html/ham/index.xml">G4FON Koch Method Morse Trainer <span>2006-5-15</span></a></li>
			<li><a href="/archives/public_html/ham/cw.html">CW Communcator 操作指南 <span>May 12, 2006</span></a></li>
		</ul>
	</div>
	<div class=foot></div>
</div>		

