
<div class="wrapper">
    <div class="mainWrap">
        <div class="main-module">
            <div class=head><H2></H2></div>
            <div class=body>
<?php if(empty($status)){ ?>


<p>
	<?php echo $status; ?>
</p>
               <tr>
                
              </tr>
<p>
    
	<input value="注册" id="submit" type="submit" />
</p>

</form>

<?php }else{ ?>
	<?php echo $status; ?>
<?php } ?>
                
            </div>
        </div>  
    </div>
    <div class="sideWrap">
        <?php $this->partial("member/sidebar") ?>
    </div>
</div>
        