        <div class="side-module">
            <div class="head"><h2>用户信息管理</h2></div>
            <div class="body">
                <ul>
                    <li><a href="/member/profile">用户详细资料</a></li>
                    <li><a href="/member/profile">消息订阅</a></li>
                    <li><a href="/member/profile">消息订阅</a></li>
                </ul>
                <div class="divider solid"></div>
                <div class="foot-links"><a href="/member/">返回用户主页</a></div>
            </div>
            <div class="foot"></div>
        </div>