	<div class="main-module">
		<div class="head"><h2>Ham Software</h2></div>
		<div class="body">
			<ul> 
				<li>RTTY - <a href="http://mmhamsoft.amateur-radio.ca/mmtty/">MMTTY RTTY - Free Amateur Radio Soundcard Software</a></li>
				<li>SSTV - <a href="http://mmhamsoft.amateur-radio.ca/mmsstv/">MMSSTV - Free Amateur Radio Soundcard Software</a></li>
				<li>PSK31 - <a href="http://www.digipan.net/">A Freeware Program for PSK31 and PSK63</a></li>
				<li><a href="http://www.echolink.org/">Echolink</a> - EchoLink® software allows licensed Amateur Radio stations to communicate with one another over the Internet, using voice-over-IP (VoIP) technology. </li>
				<li><a href="http://www.stellarium.org/">Stellarium </a> is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
It is being used in planetarium projectors. Just set your coordinates and go.</li>
				<li>You Want to Learn Morse Code? <a href="http://www.g4fon.net/">'Koch CW Trainer Version 9'</a> is A Morse Trainer using the Koch method. </li>
			</ul>
		</div>
	</div>	
	
<div class="main-module">
	<div class="head"><h2>汉化版本</h2></div>
	<div class="body"> 
		<ul>
			<li><a href="/archives/public_html/ham/index.xml">G4FON Koch Method Morse Trainer <span>2006-5-15</span></a></li>
			<li><a href="/archives/public_html/ham/cw.html">CW Communcator 操作指南 <span>May 12, 2006</span></a></li>
		</ul>
	</div>
	<div class=foot></div>
</div>		

