<div class="main-module">
    <div class=head><H2>字母解释法</H2></div>
    <div class=body>
<p>在业余无线电通讯中广泛使用英语解释法，可解决在无线电通讯中经常会碰到的由于电离层衰落所造成的声音不清楚的弊病，国际上航空管理组织（ICAO）的通讯用语也普遍使用类似的解释法。</p>
<p>由于业余电台的输出功率低，加上电波传播的复杂因素，接收到的语言信号夹有失真或衰落现象，影响了解析度。特别是DX通信时，有些不讲英语的国家的业余家口音不同，使得通话时容易发生许多误听差错，尤其是英文26个字母中，像B和P、D和T、G和J、M、N、R和I等字最容易听错。</p>
<p>为了避免这个问题的发生，全世界的电台在话音通信中均采用字母解释法，一般电台在谈到呼号、姓名或QTH(电台地点)时采用这种解释方法，以避免发生误会。国际民航组织(ICAO)的英语解释法，是美国ARRL推荐的读法，也是目前业余通信中采用的方法。也有不少的业余家用其他的字母解释法。这些字母解释单词，多数是常用词，其中有国名、地名和人名，所解释的都是单词的第一个字母。所以，熟悉英文的人，可以方便地从单词联想到相应的字母。字母解释法是话通信必须掌握的基本知识。因些，对初踏入业余无线电领域的初学者设立收听台，应先学会字母解释法，熟练掌握，才能顺利地收听话音通信。</p>
<p>在日常生活中，人们打电话时往往要对一些重要的字或词进行解释，以使对方能准确无误的记录下来，对汉字进行解释的方法大家都比较熟悉。同样我们拼读某些英文词组以便对方能记录下来时，也需要一种解释的方法。人们常说“A”A-B-C 的“A”；“C”A-B-C 的“C”等等。但我们不能都用按顺序读字母的方式进行解释，因为位于26个字母中间部分的一些字母，如果也用这种方法进行解释，无疑是既不方便，又容易混淆的。所以，ITU 规定了一些人们比较熟悉的名词分别来解释 26 个英文字母。</p>
<p>例如：“C”用 Charlie 来进行解释，R，J分别用 Romeo 与 Juliett 进行解释等。这种解释，在业余电台用话的通信联络中是必不可少的。如呼号 BY1PK ，除了按英文读法报出“B-Y-ONE-P-K”以外还应对字母进行逐个的解释，即“B-Y-ONE-P-K，BRAVO-YANKEE-ONE-PAPA-KILO“，如果一遍不够，可以从头在解释一遍。除ITU规定的解释法外，在实际工作中，我们往往还能听到很多不规则的解释法。这种不规则的解释法没有统一的规定，但必须是大家非常熟悉的名词，而起首字母必须与被解释的字母相同。</p>
<table>
		<tr>
            <td align="center"><font size="2">字母</font></td>
            <td align="center"><font size="2">标准解释法</font></td>
            <td align="center"><font size="2">其他解释法</font></td>
            <td align="center"><font size="2">字母</font></td>
            <td align="center"><font size="2">标准解释法</font></td>

            <td align="center"><font size="2">其他解释法</font></td>
        </tr>
        <tr>
            <td align="center"><font size="2">A</font></td>
            <td align="center"><font size="2">ALFA</font></td>
            <td align="center"><font size="2">AMERICA</font></td>
            <td align="center"><font size="2">N</font></td>

            <td align="center"><font size="2">NOVEMBER</font></td>
            <td align="center"><font size="2">NORWAY</font></td>
        </tr>
       <tr>
            <td align="center"><font size="2">B</font></td>
            <td align="center"><font size="2">BRAVO</font></td>
            <td align="center"><font size="2">BOSTON</font></td>

            <td align="center"><font size="2">O</font></td>
            <td align="center"><font size="2">OSCAR</font></td>
            <td align="center"><font size="2">ONTARIO</font></td>
        </tr>
        <tr>
            <td align="center"><font size="2">C</font></td>
            <td align="center"><font size="2">CHARLIE</font></td>

            <td align="center"><font size="2">CANADA</font></td>
            <td align="center"><font size="2">P</font></td>
            <td align="center"><font size="2">PAPA</font></td>
            <td align="center"><font size="2">PETER</font></td>
        </tr>
        <tr>
            <td align="center"><font size="2">D</font></td>

            <td align="center"><font size="2">DELTA</font></td>
            <td align="center"><font size="2">DENMARK</font></td>
            <td align="center"><font size="2">Q</font></td>
            <td align="center"><font size="2">QUEEC</font></td>
            <td align="center"><font size="2">QUEEN</font></td>
        </tr>

        <tr>
            <td align="center"><font size="2">E</font></td>
            <td align="center"><font size="2">ECHO</font></td>
            <td align="center"><font size="2">ENGLAND</font></td>
            <td align="center"><font size="2">R</font></td>
            <td align="center"><font size="2">ROMEO</font></td>

            <td align="center"><font size="2">RADIO</font></td>
        </tr>
         <tr>
            <td align="center"><font size="2">F</font></td>
            <td align="center"><font size="2">FOXTROT</font></td>
            <td align="center"><font size="2">FLORIDA</font></td>
            <td align="center"><font size="2">S</font></td>

            <td align="center"><font size="2">SIERRA</font></td>
            <td align="center"><font size="2">SUGAR</font></td>
        </tr>
        <tr>
            <td align="center"><font size="2">G</font></td>
            <td align="center"><font size="2">GOLF</font></td>
            <td align="center"><font size="2">GERMANY</font></td>

            <td align="center"><font size="2">T</font></td>
            <td align="center"><font size="2">TANGO</font></td>
            <td align="center"><font size="2">TOKYO</font></td>
        </tr>
        <tr>
            <td align="center"><font size="2">H</font></td>
            <td align="center"><font size="2">HOTEL</font></td>

            <td align="center"><font size="2">TONOLULU</font></td>
            <td align="center"><font size="2">U</font></td>
            <td align="center"><font size="2">UNIFORM</font></td>
            <td align="center"><font size="2">UNITED</font></td>
        </tr> 
         <tr>
            <td align="center"><font size="2">I</font></td>

            <td align="center"><font size="2">INDIA</font></td>
            <td align="center"><font size="2">ITALY</font></td>
            <td align="center"><font size="2">V</font></td>
            <td align="center"><font size="2">VICTOR</font></td>
            <td align="center"><font size="2">VIRGINIA</font></td>
        </tr>

        <tr>
            <td align="center"><font size="2">J</font></td>
            <td align="center"><font size="2">JULIET</font></td>
            <td align="center"><font size="2">JAPAN</font></td>
            <td align="center"><font size="2">W</font></td>
            <td align="center"><font size="2">WHISKEY</font></td>

            <td align="center"><font size="2">WASHINGTON</font></td>
        </tr>        
        <tr>
            <td align="center"><font size="2">K</font></td>
            <td align="center"><font size="2">KILO</font></td>
            <td align="center"><font size="2">KILOWATT</font></td>
            <td align="center"><font size="2">X</font></td>

            <td align="center"><font size="2">X-RAY</font></td>
            <td align="center"><font size="2">-</font></td>
        </tr>        <tr>
            <td align="center"><font size="2">L</font></td>
            <td align="center"><font size="2">LIMA</font></td>
            <td align="center"><font size="2">LONDON</font></td>

            <td align="center"><font size="2">Y</font></td>
            <td align="center"><font size="2">YANKEE</font></td>
            <td align="center"><font size="2">YOKOHAMA</font></td>
        </tr>        <tr>
            <td align="center"><font size="2">M</font></td>
            <td align="center"><font size="2">MIKE</font></td>

            <td align="center"><font size="2">MEXICO</font></td>
            <td align="center"><font size="2">Z</font></td>
            <td align="center"><font size="2">ZULO</font></td>
            <td align="center"><font size="2">ZANZIBAR</font></td>
        </tr>
      </table>    
        <img src="/img/radio/FAA_Phonetic_and_Morse_Chart2.svg" alt="{#phonetic#}" />
    </div>
</div>