{if $locale eq 'zh-cn'}
<div class="main-module">
  <div class=head>
    <H2>通信用Q简语（有*者为常用简语）</H2>
  </div>
  <div class=body>
    <table align="center" border="1" cellspacing="0" width="100%">
      <tbody>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">简语</p>
            </div></td>
          <td width="43%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">问句</p>
            </div></td>
          <td width="42%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">答句或报告</p>
            </div></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRA</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你台的名称是什么？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我台的名称是--</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRG</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你可否将我（或--）的准确频率见告？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你（或--）的准确频率是--。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRH</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我的频率稳定吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你的频率不稳定。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRI</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我发送的音调如何？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你发送的音调<br>
              1、良好<br>
              2、不稳</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRK</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我的（或--的）信号清晰度怎样？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你的（或--的）信号清晰度是<br>
              1、劣<br>
              2、差<br>
              3、可<br>
              4、良<br>
              5、优</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRL</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你忙吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我很忙（或与--很忙）。请不要干扰。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRM</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你受到干扰吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我现在正受到--干扰<br>
              1、无<br>
              2、稍有<br>
              3、中等的<br>
              4、严重的<br>
              5、极端的</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRN</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你受到天电干扰吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我正受到--天电干扰<br>
              1、无<br>
              2、稍有<br>
              3、中等的<br>
              4、严重的<br>
              5、极端的</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRO</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我增加发信机功率吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请增加发信机功率</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRP</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我减低发信机功率吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我减低发信机功率吗？</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRQ</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我发得快点吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请发得快点（每分钟--字）</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRS</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我发得慢一些吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请发得慢一些（每分钟--字）</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRT</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我停止拍发吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请停止拍发。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRU</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你有什么发给我吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我没有什么发给你。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRV</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你准备好了吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我已准备好。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QRW</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我通知--你正在用--kHz（或MHz）呼叫他吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请通知--我正在用--kHz（或MHz）呼叫他吗？</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRX</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你什么时候再呼叫我？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我将在--点钟再呼叫你。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QRZ</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">谁在呼叫我？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">--正用--呼叫你。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSA</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我（或--）的信号强度怎样？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你（或--）的信号强度是--<br>
              1、几乎不能收听<br>
              2、弱<br>
              3、还好<br>
              4、好<br>
              5、很好</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSB</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我的信号有衰落吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你的信号有衰落。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSD</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我的电键发报有毛病吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你的电键发报有毛病。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSK</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">在你发信号中间能否收听到我？<br>
              如果能，我能插入你的发送吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">在我发信号中间能收听到你，<br>
              你可以插入我的发送。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QSL</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你能承认收妥吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我现在承认收妥。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSN</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你在--kHz（或MHz）上听到我（或--（呼号））吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我已在--kHz（或MHz）上听到你（或--（呼号））吗？</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QSO</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你能否和--直接（或必须经过接转）通信？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我能和--直接（或必须经过接转）通信。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSP</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你可否免费转发到--？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我可以免费转发到--。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSV</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我用这个频率（或用--kHz（或MHz））拍发一连串的V字吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请用这个频率（或用--kHz（或MHz））拍发一连串的V字吗？</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSX</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你将用--kHz（或MHz）收听--（呼号）吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我正用--kHz（或MHz）收听--（呼号）。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QSY</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我改用别的频率拍发吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请改用别的频率拍发。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QSZ</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我将每字或每组拍发一次以上吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请将每字或每组拍发两次（或--次）</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">*QTH</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">你的位置在那个经度和纬度（或根据其他标志）？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">我的位置是经度--纬度--（或根据其他标志）。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QTR</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">现在的准确时间是什么？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">现在的准确时间是--点钟。</p></td>
        </tr>
        <tr>
          <td width="15%"><div align="center">
              <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">QTV</p>
            </div></td>
          <td width="43%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">要我在--kHz（或MHz）上（自--至--点钟）守听你吗？</p></td>
          <td width="42%"><p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">请在--kHz（或MHz）上（自--至--点钟）守听我。</p></td>
        </tr>
      </tbody>
    </table>
    <p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt;">　</p>
  </div>
</div>
{else}
<div class="main-module">
  <div class=head>
    <H2>Amateur Radio Q-Codes</H2>
  </div>
  <div class=body>
    <P> 
    <B>
    <center>
      <font face="comic sans ms" size="6"> <B><SPAN>Amateur Radio Q-Codes</SPAN></B></font>
    </center>
    <br>
    <br>
    <P>
    <FONT FACE="comic sans ms" SIZE=2 ><b> International Q Code is an abbreviated way to exchange a great deal of information with a simple code. <BR>
    <P> The Q Code consists of three-letter groups with each group having a specific meaning.  Each group begins with the letter Q.  Auxiliary letter groups or numbers are also used to help define the information that is need or passed with certain Q Code three-letter groups. <BR>
    <P> The International Q Code can be arranged in three types of code groups according to the second letter in the three-letter Q Code. <BR>
    <P> The Q Code comprises :
    <P> A. General Codes, second letter of which is R, S, T or U.  (Some used by Hams). <BR>
    <P> B. Maritime Service Codes, second letter of which is O, P or Q. <BR>
    <P> C. Aeronautical Codes, second letter of which is A, B, C, D, E, F, G, H, I, J, K, L, M or N. <br>
      <br>
      <center>
      </center>
      <br>
      Presented in the table below are some common Q-Codes used by radio amateurs. <BR>
    <P> These codes were found on the inside cover of a 1965 ARRL Amateur Radio Station Log Book. <BR>
    <P> Q Codes marked with an " <FONT COLOR="#FF0000">*</FONT> " are the most commonly used today.  A question is indicated by the use of the interrogation sign, " ? ", after the Q signal. <br>
      <br>
    </B>
    <TABLE BORDER=10 CELLPADDING=8    BGCOLOR="#009C63">
      <TR>
        <TD><TABLE BORDER=10 CELLPADDING=6 CELLSPACING=6 BGCOLOR=ffffff>
            <CAPTION>
            <B><FONT SIZE=5>The Amateur Radio Q-Code</FONT></B>
            </CAPTION>
            <TR ALIGN=CENTER>
              <TH>Signal</TH>
              <TH>Question</TH>
              <TH>Answer, Advice or Order</TH>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRG</B></TD>
              <TD ALIGN=LEFT>Will you indicate my exact frequency in kilocycles?</TD>
              <TD ALIGN=LEFT>Your frequency is ... kc.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRH</B></TD>
              <TD ALIGN=LEFT>Does my frequency vary?</TD>
              <TD ALIGN=LEFT>Your frequency varies.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRI</B></TD>
              <TD ALIGN=LEFT>How is the tone of my transmission?</TD>
              <TD ALIGN=LEFT>The tone of your transmission is ...<BR>
                1. Good.<BR>
                2. Variable.<BR>
                3. Bad.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRJ</B></TD>
              <TD ALIGN=LEFT>Are you receiving me badly?  Are my signals weak?</TD>
              <TD ALIGN=LEFT>I cannot receive you.  Your signals are too weak.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRK</B></TD>
              <TD ALIGN=LEFT>What is the legibility of my signals (1 to 5)?</TD>
              <TD ALIGN=LEFT>The legibility of your signals is ... (1 to 5).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRL <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Are you busy?</TD>
              <TD ALIGN=LEFT>I am busy (or busy with....).   Please do not interfere.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRM <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Are you being interfered with?</TD>
              <TD ALIGN=LEFT>I am being interfered with.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRN <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Are you troubled by static?</TD>
              <TD ALIGN=LEFT>I am troubled by static.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRO <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Must I increase power?</TD>
              <TD ALIGN=LEFT>Increase power.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRP <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Must I decrease power?</TD>
              <TD ALIGN=LEFT>Decrease power.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRQ <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Must I send faster?</TD>
              <TD ALIGN=LEFT>Send faster ... (words per min.).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRS <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Must I send more slowly?</TD>
              <TD ALIGN=LEFT>Transmit more slowly ... (w.p.m.).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRT <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Must I stop transmission?</TD>
              <TD ALIGN=LEFT>Stop transmission.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRU <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Have you anything for me?</TD>
              <TD ALIGN=LEFT>I have nothing for you.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRV <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Are you ready?</TD>
              <TD ALIGN=LEFT>I am ready.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRW</B></TD>
              <TD ALIGN=LEFT>Must I advise ... that you are calling him on ... kc?</TD>
              <TD ALIGN=LEFT>Please advise ... that I am calling him on ... kc.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRX <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>When will you call again?</TD>
              <TD ALIGN=LEFT>I will call you again at ... hours (on ... kc.).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRZ <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>By whom am I being called?</TD>
              <TD ALIGN=LEFT>You are being called by ...</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSA</B></TD>
              <TD ALIGN=LEFT>What is the strength of my signals (1 to 5)?</TD>
              <TD ALIGN=LEFT>The strength of your signals is ... (1 to 5).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSB <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Does the strength of my signals vary?</TD>
              <TD ALIGN=LEFT>The strength of your signals varies.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSD</B></TD>
              <TD ALIGN=LEFT>Is my keying correct? Are my signals distinct?</TD>
              <TD ALIGN=LEFT>Your keying is incorrect; your signals are bad.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSG</B></TD>
              <TD ALIGN=LEFT>Must I transmit ... telegrams (or one telegram) at a time?</TD>
              <TD ALIGN=LEFT>Transmit ... telegrams (or one telegram) at a time.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSK <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Shall I continue the transmission of all my traffic?</TD>
              <TD ALIGN=LEFT>I can hear you between my signals.  Continue: I shall interrupt you if necessary.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSL <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Can you acknowledge receipt?</TD>
              <TD ALIGN=LEFT>I am acknowledging receipt.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSM</B></TD>
              <TD ALIGN=LEFT>Shall I repeat the last telegram I sent you?</TD>
              <TD ALIGN=LEFT>Repeat the last telegram you sent me.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSO <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Can you communicate with ... directly (or through...)?</TD>
              <TD ALIGN=LEFT>I can communicate with ... direct (or through...).</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSP</B></TD>
              <TD ALIGN=LEFT>Will you relay to ...?</TD>
              <TD ALIGN=LEFT>I will relay to ... free of charge.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSV</B></TD>
              <TD ALIGN=LEFT>Shall I send a series of VVV....?</TD>
              <TD ALIGN=LEFT>Send a series of VVV.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSX</B></TD>
              <TD ALIGN=LEFT>Will you listen for ... (call sign) on ... kcs?</TD>
              <TD ALIGN=LEFT>I am listening for ... on ... kcs.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSY <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>Shall I change to ... kilocycles without changing the type of wave?</TD>
              <TD ALIGN=LEFT>Change to ... kc. without changing type of wave.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QSZ</B></TD>
              <TD ALIGN=LEFT>Shall I send each word or group twice?</TD>
              <TD ALIGN=LEFT>Send each word or group twice.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QTA</B></TD>
              <TD ALIGN=LEFT>Shall I cancel nr ... as if it had not been sent?</TD>
              <TD ALIGN=LEFT>Cancel nr ... as if it had not been sent.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QTB</B></TD>
              <TD ALIGN=LEFT>Do you agree with my word count?</TD>
              <TD ALIGN=LEFT>I do not agree with your word count; I shall repeat the first letter of each word and the first figure of each number.</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QTC</B></TD>
              <TD ALIGN=LEFT>How many telegrams have you to send?</TD>
              <TD ALIGN=LEFT>I have ... telegrams for you or for ....</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QTH <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT>What is your position (location)?</TD>
              <TD ALIGN=LEFT>My position (location) is ....</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QTR</B></TD>
              <TD ALIGN=LEFT>What is the exact time?</TD>
              <TD ALIGN=LEFT>The exact time is ....</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QST <FONT COLOR="#FF0000">*</FONT></B></TD>
              <TD ALIGN=LEFT></TD>
              <TD ALIGN=LEFT>General call preceeding a message address to all amateurs and A.R.R.L. Members.  This is in effect "CQ ARRL".</TD>
            </TR>
            <TR ALIGN=CENTER>
              <TD><B>QRRR</B></TD>
              <TD ALIGN=LEFT></TD>
              <TD ALIGN=LEFT>Official A.R.R.L. "land SOS."  A distress call for emergency use only.</TD>
            </TR>
          </TABLE></TD>
      </TR>
    </TABLE>
  </div>
</div>
{/if}