<div class="wrapper">

<div class="mainWrap">

	<div class="main-module">
		<div class="head"><h2><?php echo $year ?> - 著作权所有，禁止转载，禁止商业用途，商业用途，请联系本人。</h2></div>
		<div class="body">
		</div>
	</div>
	

	<div style="margin-left:5px;float:left;display:inline;">
		<?php  foreach ($collections as $collection) { ?>

          <div style="width:165px;height:200px;background:#EEE;border:1px solid #ccc;text-align:center;float:left;margin:0 0 5px 5px;display:inline;overflow:hidden;">
            <div style="width:128px;margin:5px;">
                <a href="/photography/album/<?php echo $collection ?>/" rel="nofollow">
                    <img src="/photography/album/<?php echo $collection ?>/" alt="Thumbnail..."/>
                </a>
            </div>
          </div>		
		
		<?php } ?>
	</div>

		<!--
		<div class="gumball">
			<a href="/{$locale}/photography/collection/maximize/{$history}/{$album_key}/{$row}">
			<img src="/{$locale}/photography/collection/thumbnail/{$history}/{$album_key}/{$row}" alt="loading thumbnail..."/>
			</a>
		</div>
		-->
	
	<br clear="all" />
	<div class="default_page_nav">
		<div class="wrap">
			<div class="pages">
			Page {$pager.number} ... {$pager.total} 
			</div>
			<div class="page_flipper">
			« {$pager.first} | {$pager.previous} | {$pager.next} | {$pager.last}»
			</div>
		</div>
	</div>

	<div class="main-module">
		<div class="head"><h2>原创文档</h2></div>
		<div class="body">
			<div class="divider">&nbsp;</div>
		</div>
		<div class="foot"></div>
	</div>
	

</div>
<div class="sideWrap">
	<div class="side-module">
	  <div class="head">
		<h2>Photo albums - <?php echo $year ?></h2>
	  </div>
	  <div class="body">
	  <?php if($collections){ ?>
		<ul>
		<?php  foreach ($collections as $collection) { ?>
			<li>
				<a href="/photography/album/<?php echo $collection ?>/"><?php echo $collection ?></a>
			</li>
		<?php } /* <a href="/{$locale}/photography/collection/album/{$history}/{$md5}/"><b style="color:orange">{$album}</b></a> */ ?>
		</ul>
		<?php } ?>
		<div class="divider solid"></div>
		<div class="foot-links"><a href="/archives/public_html/photography/palm/index.html">Netkiller Photography 手札</a> </div>
	  </div>
	  <div class="foot"></div>
	</div>
</div>

</div>





