	<div class="main-module">
		<div class="head"><h2>DTMF 信令</h2></div>
		<div class="body">

		</div>
	</div>	

<table>
   <thead>
       <th>callsign</th>
       <th>DTMF</th>
   </thead>
   <tbody>
       <?php foreach($signalings as $signaling){ ?>
       <tr>
           <td><a href="/{$locale}/radio/logs/{$signaling->callsign|lower}.html"><?php echo $signaling->callsign ?></td>
           <td><?php echo $signaling->dtmf ?></td>
       </tr>
       <?php }?>
   </tbody>
</table>