	<div class="main-module">
		<div class="head"><h2>信令列表</h2></div>
		<div class="body">

<table width="100%">
   <thead>
       <th>Callsign</th>
       <th>Mototrbo</th>
       <th>MDC1200</th>
       <th>Quik-Call II</th>
       <th>DTMF</th>
       <th>Select V</th>
       <th>Yaesu(C4FM)</th>
   </thead>
   <tbody>
       <?php foreach($signalings as $signaling){ ?>
       <tr>
           <td><a href="/radio/index/qrz/<?php echo $signaling->callsign ?>"><?php echo $signaling->callsign ?></td>
           <td><?php echo @$signaling->mototrbo ?></td>
           <td><?php echo @$signaling->mdc1200 ?></td>
           <td><?php echo @$signaling->qcii ?></td>
           <td><?php echo @$signaling->dtmf ?></td>
           <td><?php echo @$signaling->selectv ?></td>
           <td><?php echo @$signaling->c4fm ?></td>
       </tr>
       <?php }?>
   </tbody>
</table>

		</div>
	</div>
