<div id="fullContainer">
<div id="bigContainer">
	<div class=main-module id=tagging>
		<div class=head><H2>Popular Lens</H2></div>
		<div class=body>
			<img width="200" src="/img/equipment/Canon%20EF%2016-35MM%20F2.8L%20II%20USM.jpg"/>
			<img width="200" src="/img/equipment/Canon%20EF%2016-35MM%20F2.8L%20II%20USM%20(MTF).jpg"/>
			<br/>
			<img width="200" src="/img/equipment/Canon EF 24-105 f4.0L IS USM.jpg"/>
			<img width="200" src="/img/equipment/Canon EF 24-105 f4.0L IS USM (MTF).jpg"/>
		</div>
	</div>
	<div class="main-module">
		<div class="head"><h2>原创文档</h2></div>
		<div class="body">

	   	</div>
		<div class="foot"></div>
	</div>
</div>
<div id="smallContainer">
<div class="side-module">
	<div class="head"><h2> 最进更新 </h2></div>
	<div class="body">
		<a href="/{$locale}/photography/gallery/album/2009/4de8f1e29555b75ac78e0cf5b1bd9d7d/"><img src="/{$locale}/photography/home/images/slides.jpg" width="278" /></a>
   	</div>
	<div class=foot></div>
</div>

<div class="side-module">
	<div class="head"><h2> 最进更新 </h2></div>
	<div class="body">
		<ul>
			<li><a href="http://picasaweb.google.com/bg7nyt/">摄影作品</a></li> 
			<li><a href="http://openx.photo.163.com">我的相册</a></li>
			<li><a href="http://www.youtube.com/user/bg7nyt">我的视频</a></li> 		
		<ul>
   	</div>
	<div class="foot"></div>
</div>

	<div class="side-module">
		<div class=head><h2> Sort by lens </h2></div>
		<div class=body>
			<ul>
			{foreach from=$Categorys item=category}
	      		<li {if $photocategory eq $category->id} class="on" {/if} ><a href="/{$locale}/photography/category/{$category->id}/">{$category->title}</a> </li>
			{/foreach}
			</ul>
	   	</div>
		<div class=foot></div>
	</div>
	
	<div class="side-module">
	  <div class=head> <h2> Sort By camera </h2> </div>
	  <div class=body>
	  	<ul>
	  		<li {if $mainmenu eq 'photo'} class="on" {/if} ><a href="/{$locale}/photography/library/"  target="_parent">{#photo_library#}</a></li>
			<li {if $mainmenu eq 'trip'} class="on" {/if} ><a href="/{$locale}/trip/" target="_parent">{#travel_photography#}</a></li>
			<li><a href="/{$locale}/purchase/" target="_parent">{#purchase#}</a></li>
		</ul>    
	    <div class="divider solid"></div>
	    <div class=foot-links><a href="#">100 most popular photos</a></div>
	  </div>
	  <div class=foot></div>
	</div>


	
</div>
</div>	


