<!DOCTYPE html>
<html>
<head>
	<?php echo $this->tag->getTitle() ?>
</head>
<body>

<div class="sidebar">
<ul class="menu">
    <li><a href="/">Home</a></li>
    <li><a href="/articles">Articles</a></li>
    <li><a href="/contact">Contact us</a></li>
</ul>
</div>
<?php $this->partial("shared/header") ?>	
<div class="container">
	<?php echo $this->getContent() ?>
</div>	

<?php $this->partial("shared/footer") ?>	
	
</body>
</html>