<div class="wrapper">    
    <div class="mainWrap">
        <div class="wrapper">

<?php if($repeater){?>
<div class="main-module">
	<div class="head"><h2><?php echo $repeater->name?> 中继台信号覆盖区</h2></div>
	<div class="body"> 

<style type="text/css">
#map {
    /* height: 180px; */
    width: 700px; 
    height: 600px;
} 
</style>

<div id="map"></div>

<script type="text/javascript">
var map = new BMap.Map("map");
var point = new BMap.Point(<?php echo $repeater->coordinate?>);
map.centerAndZoom(point, 12);
map.enableScrollWheelZoom();  
var marker = new BMap.Marker(point);
map.addOverlay(marker);
var circle = new BMap.Circle(point,70000,{strokeColor:"blue",fillColor:"blue",strokeWeight:1, strokeStyle:"dashed", strokeOpacity:0.5, fillOpacity: 0.05});
map.addOverlay(circle);
var circle = new BMap.Circle(point,40000,{strokeColor:"yellow",fillColor:"yellow",strokeWeight:1, strokeStyle:"dashed", strokeOpacity:0.5, fillOpacity: 0.2});
map.addOverlay(circle);
var circle = new BMap.Circle(point,20000,{strokeColor:"blue",fillColor:"blue",strokeWeight:1, strokeStyle:"solid", strokeOpacity:0.5, fillOpacity: 0.1});
map.addOverlay(circle);
var circle = new BMap.Circle(point,10000,{strokeColor:"green",fillColor:"green",strokeWeight:1, strokeStyle:"solid", strokeOpacity:0.5, fillOpacity: 0.1});
map.addOverlay(circle);
var circle = new BMap.Circle(point,5000,{strokeColor:"red",fillColor:"red",strokeWeight:1, strokeStyle:"solid", strokeOpacity:0.5, fillOpacity: 0.2});
map.addOverlay(circle);

</script>

		从最内测向外依次是,0.5w 手台,2W手台,5W手台+Yagi/5W车台+GP天线，车台全功率，罕见的成功通联。
		最外侧两个灰色覆盖区是，梧桐山顶手台覆盖区和罕见成功通联，曾经有火腿通联成功。
	</div>
	<div class=foot></div>
</div>	        
   

<div class="side-module">
	<div class="head"><h2><?php echo $repeater->name?></h2></div>
	<div class="body">
        <ul>
            
            <li>位置: <?php echo $repeater->province?> <?php echo $repeater->city?></li>
            <li>频率: <?php echo $repeater->frequency?></li>
            <li>差频: <?php echo $repeater->shift?></li>
            <li>静噪: <?php echo $repeater->squelch?></li>
            <li>哑音: <?php echo $repeater->code?></li>
            <li>坐标: <?php echo $repeater->coordinate?></li>
            <li>分区: <?php echo $repeater->zone['cq']?>,<?php echo $repeater->zone['itu']?></li>
            <li>台主: <?php echo $repeater->owner?></li>
            <li>图片: <?php echo $repeater->image?></li>
            <li>状态: <?php echo $repeater->status?></li>
            <li>描述: <?php echo $repeater->description?></li>
        </ul> 	
   	</div>
	<div class="foot"></div>
</div>
<?php }?>     

    </div>
    <div class="sideWrap">
        <div class="side-module">
          <div class="head">
            <h2>业余无线电中继台</h2>
          </div>
          <div class="body">
                <ul>
                <?php foreach ($stationlists as $station){?>
                    <li>
                         <a href="/radio/repeater/details/<?php echo $station->_id;?>"><?php echo $station->frequency;?> <?php echo $station->name;?></a>
                    </li>
                <?php }?>
                </ul>
                <div class="divider solid"></div>
            <div class="foot-links"><a href="/radio/repeater/">全国中继台覆盖图</a> </div>
          </div>
          <div class="foot"></div>
        </div>
    </div>
</div>