<div id="bigContainer">

	<div class=main-module id=tagging>
		<div class=head><h2>What is Amateur Radio?</h2></div>
		<div class=body>

			<a href="http://www.hello-radio.org/">Learn more about ham radio, why people love it, and find out how you can become a ham!</a>

		</div>
	</div>

	<div class="main-module">
		<div class="head"><h2>Ham Activity</h2></div>
		<div class="body">
			<p><img src="/images/radio/ham.png" style="float:left;" />
			<ul style="list-style:none;">
				<li><a href="/archives/radio/activity/wutong.xml">QSO around Zhu Jiang delta region [ December 1, 2008]</a></li>
				<li><a href="/archives/radio/activity/The antenna heaven.xml">The antenna heaven [December 8, 2008]</a></li>
				<li><a href="/archives/radio/activity/difficult.xml">Why is it so difficult QSO with ham of China on the HF [December 10, 2008]</a></li>
				<li><a href="/archives/radio/activity/memoirs.xml">A ham's memoirs [December 12, 2008]</a></li>
			</ul>
			</p>
		</div>
	</div>
    <div class="main-module">
        <div class=head><H2>LATEST NEWS</H2></div>
        <div class=body>
            <ol>
            <?php foreach ($messages as $message){?>
                <li><?php echo $message->datetime;?> <?php echo $message->content;?></li>
            <?php }?>
            </ol>
        </div>
        <div class="foot"></div>
    </div>

</div>

<div id="smallContainer">

<div class="side-module">
	<div class="head"><h2>呼号查询</h2></div>
	<div class="body">
		<form method="get" name="qrz" id="qrz">
		callsign <input type="text" id="qrz" name="qrz" value="" size="6" maxlength="6" />
		<input type="submit" value="search" id="go" name="go"/>
		</form>
	</div>
	<div class=foot></div>
</div>
<div id="dashboard">
</div>


<div class="side-module">
	<div class="head"><h2>QSO {#ranging#}</h2></div>
	<div class="body">
		<form method="post" name="qsoform" id="qsoform">
		{#callsign#} <input type="text" id="qso" name="qso" value="BG7NYT-BI7JMS-BH7MXG" onclick="this.value='';"size="18" maxlength="20" />
		<input type="submit" value="{#ranging#}" id="ranging" name="ranging"/><br />
		使用“-”分割呼号,呼号个数不限制。
		<form>
	</div>
	<div class=foot></div>
</div>

<div class=side-module>
	<div class=head><H2>Welcome to QSO</H2></div>
	<div class=body>
		<ul>
		  <li>Personal Amateur Radiostations of P.R.China</li>
		  <li>ZONE CQ24 ITU44 ShenZhen, China</li>
		  <li>QTH: Longhua Shenzhen, China</li>
		  <li>Callsign: BG7NYT No.72-50335</li>
		  <li>Best Regards, VY 73! OP. BG7NYT</li>
		</ul>
   	</div>
	<div class=foot></div>
</div>
<div class=side-module>
	<div class=head><H2>Ham {#resource#}</H2></div>
	<div class=body>
		<ul>
		  <li><a href="/{$locale}/radio/placemark/ham.kml">Google Earth Placemark (KML)</a></li>
		  <li><a href="/{$locale}/radio/placemark/ham.kmz">Google Earth Placemark (KMZ)</a></li>
		</ul>
   	</div>
	<div class=foot></div>
</div>
<div class=side-module>
	<div class=head><H2>Links</H2></div>
	<div class=body>
		<ul>
		  <li>http://www.iaru.org/</li>
		  <li>http://www.qrz.com/</li>
		  <li>http://www.qrz.cn/</li>
		  <li>http://www.szham.org</li>
		  <li>http://www.hellocq.net</li>
		  <li>http://www.hellocq.com</li>

		</ul>
   	</div>
	<div class=foot></div>
</div>

</div>
